name: Update Badges

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  do-stuff:
    name: Do Stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Clear Badges
        run: rm -rf users/*
      
      - name: Update Enmity Badges
        run: node scripts/getEnmityBadges.mjs
      
      - name: Update Velocity Badges
        run: node scripts/getVelocityBadges.mjs
      
      - name: Update Vencord Badges
        run: node scripts/getVencordBadges.mjs
      
      - name: Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Updated Badges" || exit 0
          git push